#!/usr/bin/env python3
"""Slice a mascot sprite sheet into individually numbered tiles.

Run manually; see art/README.md for the two-pass workflow (slice, tag by hand,
re-run to emit the Kotlin list).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from PIL import Image

MAX_EDGE = 256
MIN_TILE_EDGE = 32
WEBP_QUALITY = 90
WEBP_METHOD = 6


def boundaries(total: int, n: int) -> list[int]:
    """Round-half-up partition of ``total`` into ``n`` parts.

    The parts exactly cover ``0..total`` with no gap, overlap or dropped pixel,
    which is what lets a sheet whose width is not a multiple of the column count
    be sliced without cropping.
    """
    return [(i * total + n // 2) // n for i in range(n + 1)]


def parse_size(text: str) -> tuple[int, int]:
    parts = text.lower().split("x")
    if len(parts) != 2:
        raise ValueError(f"expected WxH, got {text!r}")
    width, height = (int(part) for part in parts)
    if width < 1 or height < 1:
        raise ValueError(f"expected positive dimensions, got {text!r}")
    return width, height


def slice_sheet(image: Image.Image, cols: int, rows: int, skip: set[int]):
    """Yield ``(tile_number, tile)`` in reading order, 1-based, omitting ``skip``."""
    xs = boundaries(image.width, cols)
    ys = boundaries(image.height, rows)
    for index in range(cols * rows):
        number = index + 1
        if number in skip:
            continue
        row, col = divmod(index, cols)
        yield number, image.crop((xs[col], ys[row], xs[col + 1], ys[row + 1]))


def _fit(tile: Image.Image) -> Image.Image:
    longest = max(tile.width, tile.height)
    if longest <= MAX_EDGE:
        return tile
    scale = MAX_EDGE / longest
    size = (max(1, round(tile.width * scale)), max(1, round(tile.height * scale)))
    return tile.resize(size, Image.LANCZOS)


def write_tiles(tiles, out_dir: Path) -> list[str]:
    out_dir.mkdir(parents=True, exist_ok=True)
    filenames = []
    for number, tile in tiles:
        filename = f"mascot_{number:02d}.webp"
        _fit(tile).convert("RGB").save(
            out_dir / filename, "WEBP", quality=WEBP_QUALITY, method=WEBP_METHOD
        )
        filenames.append(filename)
    return filenames


def write_catalogue_skeleton(path: Path, filenames: list[str]) -> bool:
    """Write an unreviewed skeleton catalogue, or leave an existing one untouched.

    Returns True when a skeleton was written.
    """
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    skeleton = [{"file": name, "tag": "", "description": ""} for name in filenames]
    path.write_text(json.dumps(skeleton, indent=2) + "\n", encoding="utf-8")
    return True


def _escape(text: str) -> str:
    for char in ("\\", '"', "$"):
        text = text.replace(char, "\\" + char)
    return text


def emit_kotlin(entries: list[dict]) -> str:
    lines = [
        "// Generated by tools/slice_mascot.py from art/mascot-sprites.json"
        " — do not edit by hand.",
        "listOf(",
    ]
    for entry in entries:
        drawable = Path(entry["file"]).stem
        lines.append(
            f'    MascotSprite("{_escape(entry["tag"])}",'
            f' "{_escape(entry["description"])}", R.drawable.{drawable}),'
        )
    lines.append(")")
    return "\n".join(lines)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("sheet", help="path to the sprite sheet")
    parser.add_argument("--cols", type=int, required=True)
    parser.add_argument("--rows", type=int, required=True)
    parser.add_argument(
        "--expect-size",
        required=True,
        metavar="WxH",
        help="the sheet's expected pixel size; a mismatch aborts the run",
    )
    parser.add_argument(
        "--skip",
        type=int,
        nargs="+",
        default=[],
        metavar="N",
        help="tile numbers to leave unwritten; survivors keep their numbers",
    )
    parser.add_argument(
        "--out-dir", type=Path, default=Path("app/src/main/res/drawable-nodpi")
    )
    parser.add_argument("--catalogue", type=Path, default=Path("art/mascot-sprites.json"))
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)

    try:
        expected = parse_size(args.expect_size)
    except ValueError as error:
        print(f"error: --expect-size: {error}", file=sys.stderr)
        return 2

    if args.cols < 1 or args.rows < 1:
        print(
            f"error: --cols and --rows must be at least 1, got {args.cols}x{args.rows}",
            file=sys.stderr,
        )
        return 2

    with Image.open(args.sheet) as sheet:
        return _slice(args, sheet, expected)


def _slice(args, sheet: Image.Image, expected: tuple[int, int]) -> int:
    if sheet.size != expected:
        print(
            f"error: {args.sheet} is {sheet.width}x{sheet.height},"
            f" expected {expected[0]}x{expected[1]} —"
            " the grid arithmetic does not apply, refusing to guess",
            file=sys.stderr,
        )
        return 2

    xs = boundaries(sheet.width, args.cols)
    ys = boundaries(sheet.height, args.rows)
    widths = [b - a for a, b in zip(xs, xs[1:])]
    heights = [b - a for a, b in zip(ys, ys[1:])]
    if min(widths) < MIN_TILE_EDGE or min(heights) < MIN_TILE_EDGE:
        print(
            f"error: a {args.cols}x{args.rows} grid over {sheet.width}x{sheet.height}"
            f" gives tiles as small as {min(widths)}x{min(heights)} px,"
            f" below the {MIN_TILE_EDGE} px minimum",
            file=sys.stderr,
        )
        return 2

    print(
        f"{args.cols}x{args.rows} grid -> tiles"
        f" {min(widths)}-{max(widths)} x {min(heights)}-{max(heights)} px"
    )

    skip = set(args.skip)
    written = write_tiles(slice_sheet(sheet, args.cols, args.rows, skip), args.out_dir)
    print(f"wrote {len(written)} tiles to {args.out_dir}")

    if write_catalogue_skeleton(args.catalogue, written):
        print(f"wrote skeleton catalogue {args.catalogue}")
    else:
        print(f"{args.catalogue} exists — left untouched")

    entries = json.loads(args.catalogue.read_text(encoding="utf-8"))

    catalogued = [entry["file"] for entry in entries]
    if catalogued != written:
        print(
            f"warning: {args.catalogue} lists {len(catalogued)} tiles that do not match"
            f" the {len(written)} just written — the catalogue is stale for this sheet",
            file=sys.stderr,
        )

    unreviewed = [e["file"] for e in entries if not e["tag"] or not e["description"]]
    if unreviewed:
        print(
            f"warning: {len(unreviewed)} catalogue entries still have no tag or"
            " description — look at every tile and fill them in before using this list",
            file=sys.stderr,
        )

    print()
    print(emit_kotlin(entries))
    return 0


if __name__ == "__main__":
    sys.exit(main())
